version: '2.1'
services:
  app:
    build:
      context: ./docker/app
    image: tvdocker/app:latest
    ports:
      - 8765:80
      - 443:443
    volumes:
      - .:/var/www/html:cached
    networks:
      - tvdocker_net
  redis:
    build:
      context: ./docker/redis
    image: tvdocker/redis:latest
    volumes:
      - redisdata:/data
    networks:
      - tvdocker_net

  mysql:
    build:
      context: ./docker/mysql
    image: tvdocker/mysql:latest
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tvdocker
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - tvdocker_net

volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local

networks:
  tvdocker_net:
    driver: bridge